---
format_version: '13'
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
project_type: android
workflows:
  build_apk:
    summary: Run your Android unit tests and create an APK file to install your app
      on a device or share it with your team.
    description: The workflow will first clone your Git repository, install Android
      tools, set the project's version code based on the build number, run Android
      lint and unit tests, build the project's APK file and save it.
    steps:
    - git-clone@8: {}
    - install-missing-android-tools@3:
        inputs:
        - gradlew_path: "$PROJECT_LOCATION/gradlew"
    - change-android-versioncode-and-versionname@1:
        inputs:
        - build_gradle_path: "$PROJECT_LOCATION/$MODULE/build.gradle.kts"
    - android-lint@0:
        inputs:
        - project_location: "$PROJECT_LOCATION"
        - variant: "$VARIANT"
        - cache_level: none
    - android-unit-test@1:
        inputs:
        - project_location: "$PROJECT_LOCATION"
        - variant: "$VARIANT"
        - cache_level: none
    - android-build@1:
        inputs:
        - project_location: "$PROJECT_LOCATION"
        - module: "$MODULE"
        - variant: "$VARIANT"
        - cache_level: none
    - sign-apk@2:
        run_if: '{{getenv "BITRISEIO_ANDROID_KEYSTORE_URL" | ne ""}}'
    - deploy-to-bitrise-io@2: {}
  run_tests:
    summary: Run your Android unit tests and get the test report.
    description: The workflow will first clone your Git repository, cache your Gradle
      dependencies, install Android tools, run your Android unit tests and save the
      test report.
    steps:
    - git-clone@8: {}
    - bundle::Step_bundle: {}
    - install-missing-android-tools@3:
        inputs:
        - gradlew_path: "$PROJECT_LOCATION/gradlew"
    - android-unit-test@1:
        inputs:
        - project_location: "$PROJECT_LOCATION"
        - variant: "$VARIANT"
        - cache_level: none
    - save-gradle-cache@1: {}
    - deploy-to-bitrise-io@2: {}
    triggers:
      push:
      - branch: main
      pull_request:
      - source_branch: "*"
meta:
  bitrise.io:
    stack: linux-docker-android-22.04
    machine_type_id: elite
app:
  envs:
  - PROJECT_LOCATION: "."
    opts:
      is_expand: false
  - MODULE: app
    opts:
      is_expand: false
step_bundles:
  Step_bundle:
    steps:
    - restore-gradle-cache@2:
        is_skippable: false
